language: ruby
rvm:
  - "2.3.1"
  - "2.4.1"
env:
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.10.4"
  - PUPPET_VERSION="~> 5.0.0"
sudo: false
addons:
  apt:
    packages:
      - expect
script:
  bundle exec rspec
notifications:
  email: false
matrix:
  exclude:
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 5.0.0"
branches:
  only:
    - master
    - /^v\d/